#
# The load balancer for our Java API, which exposes it over port 80
# The below host name is configured on the host PC in the /etc/hosts file
# 'kubectl get ingress' shows that ports 80 and 443 are exposed
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javaapi-ingress
spec:
  tls:
    - hosts:
        - javaapi.mycompany.com
      secretName: mycompany-com-tls
  rules:
    - host: javaapi.mycompany.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: javaapi-svc
                port:
                  number: 80