version: '3.8'
services:

  finalapi:
    image: finaljavaapi:v1
    hostname: api.authsamples-dev.com
    ports:
      - 446:8000
    volumes:
      - ../environments/docker-local.config.json:/usr/api/api.config.json
      - ../../certs/authsamples-dev.ssl.p12:/usr/api/certs/authsamples-dev.ssl.p12
